import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/nav-links'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'CURSOS',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="es">
      <body className={inter.className}>
      <div className="header">
      <Header />
    </div>
        {children}
        </body>
    </html>
  )
}
